{
    config,
    pkgs,
    ...
}:

{
    home.packages = with pkgs;[
        discord
        eog
        element-desktop
        fastfetch
        firefox
        gnome-tweaks
        go
        grim
        htop
        hugo
        jetbrains.goland
        krita
        killall
        kitty
        obs-studio
        playerctl
        protontricks
        protonup-qt
        smartmontools
        stress-ng
        telegram-desktop
        texliveFull
        texstudio
        upscayl
        wechat-uos
    ];
}