{
    pkgs,
    ...
}:

{
    environment.systemPackages = with pkgs; [
        btop
        discord
        eog
        element-desktop
        fastfetch
        firefox
        gnome-tweaks
        go
        grim
        htop
        jetbrains.goland
        krita
        killall
        mission-center
        mpv
        obs-studio
        python314
        smartmontools
        stress-ng
        telegram-desktop
        upscayl
        v2ray
        v2raya
        vscode
        wechat-uos
    ];
}