{
    pkgs,
    ...
}:

{
    environment.systemPackages = with pkgs; [
        discord
        eog
        element-desktop
        fastfetch
        firefox
        gnome-tweaks
        go
        grim
        htop
        hugo
        jetbrains.goland
        krita
        killall
        mpv
        obs-studio
        smartmontools
        stress-ng
        telegram-desktop
        upscayl
        v2ray
        v2raya
        vscode
        wechat-uos
    ];
}